# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OjOROa_ndQ65F39idjscfQ7nMKt21srj
"""

!pip install streamlit

import streamlit as st
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

from google.colab import files
uploaded = files.upload()

df=pd.read_csv("clustered_customer_data.csv")

file_name = list(uploaded.keys())[0] # Assuming only one file was uploaded

st.title("🧠 Customer Personality Segmentation Dashboard")
st.markdown("Analyze customer segments based on clustering algorithms (KMeans & DBSCAN).")

clustering_option = st.sidebar.selectbox("Select Clustering Algorithm", ["KMeans", "DBSCAN"])
cluster_col = "KMeans_Cluster" if clustering_option == "KMeans" else "DBSCAN_Cluster"

st.subheader("Dataset Overview")
st.write(df.describe())

st.subheader(f"📊 Cluster Distribution - {clustering_option}")
fig, ax = plt.subplots()
sns.countplot(x=cluster_col, data=df, palette="Set2", ax=ax)
st.pyplot(fig)

st.subheader(f"🌀 Cluster Visualization - {clustering_option} (PCA)")
fig2, ax2 = plt.subplots()
sns.scatterplot(data=df, x="PCA1", y="PCA2", hue=cluster_col, palette="Set1", ax=ax2)
plt.title(f"{clustering_option} Clusters (2D PCA)")
st.pyplot(fig2)

st.subheader("📈 Cluster Profiles")
grouped = df.groupby(cluster_col)[["Income", "Recency", "Age", "Children", "TotalSpend"]].mean()
st.dataframe(grouped.style.format("{:.2f}"))

st.download_button("Download Clustered Data", data=df.to_csv(index=False), file_name="clustered_data.csv", mime="text/csv")