# -*- coding: utf-8 -*-
"""app3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FpLRJuTyVuht4NgRNO2l-63Z29YwfMrG
"""

#!pip install streamlit

streamlit_code ="""
import streamlit as st
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
"""
import streamlit as st
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

from google.colab import files
uploaded = files.upload()

df=pd.read_csv("clustered_customer_data.csv")

st.title("🧠 Customer Personality Segmentation Dashboard")
st.sidebar.header("Select Clustering Algorithm")
algorithm = st.sidebar.selectbox("Clustering", ["KMeans", "DBSCAN"])
cluster_col = "KMeans_Cluster" if algorithm == "KMeans" else "DBSCAN_Cluster"

st.subheader("📊 Cluster Distribution")
st.bar_chart(df[cluster_col].value_counts())

st.subheader("🌀 PCA Scatter Plot")
fig, ax = plt.subplots()
sns.scatterplot(data=df, x="PCA1", y="PCA2", hue=cluster_col, palette="tab10", ax=ax)
st.pyplot(fig)

st.subheader("📈 Cluster KPIs")
st.dataframe(df.groupby(cluster_col)[["Income", "Age", "TotalSpend"]].mean())

with open("app3.py", "w") as f:
    f.write(streamlit_code)

# 3. Download the file
from google.colab import files
files.download("app3.py")