# -*- coding: utf-8 -*-
"""kmeans.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14ATdeqmBgvJMv2JBJvsK5skO5TjVqjsi
"""

import pandas as pd
import numpy as np
import pickle
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans

from google.colab import files
uploaded = files.upload()

df = pd.read_excel("marketing_campaign1.xlsx")

df["Dt_Customer"] = pd.to_datetime(df["Dt_Customer"], errors='coerce')
df["Age"] = 2025 - df["Year_Birth"]
df["Children"] = df["Kidhome"] + df["Teenhome"]
product_cols = ["MntWines", "MntFruits", "MntMeatProducts", "MntFishProducts", "MntSweetProducts", "MntGoldProds"]
df["TotalSpend"] = df[product_cols].sum(axis=1)
df.drop(columns=["ID", "Year_Birth", "Z_CostContact", "Z_Revenue"], inplace=True)
df["Income"].fillna(df["Income"].median(), inplace=True)

features = ["Income", "Recency", "Age", "Children", "TotalSpend"]
X = df[features]

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

kmeans_model = KMeans(n_clusters=4, random_state=42)
kmeans_model.fit(X_scaled)

with open("kmeans_model.pkl", "wb") as f:
    pickle.dump(kmeans_model, f)

print("✅ Pickle file saved as kmeans_model.pkl")

from google.colab import files
files.download("kmeans_model.pkl")